### ISSUE TITLE
TypeError: awesome_phonenumber_1.default.getSupportedRegionCodes is not a function

### ISSUE THREAD

**Issue by chris-findlay** [grantila/awesome-phonenumber#38]
Not sure why, but the build after my PR to add `getSupportedRegionCodes` (2.14.0), while that shows up in the `index.d.ts` doesn't appear to be present in the actual code.

Does it need a test or something to call it so it doesn't get trimmed?

**Comment by chris-findlay** [comment]
Additionally I'm having the following trying to build it locally:

```
...
[11:55:58] Finished 'build-deps' after 19 s
[11:55:58] Starting 'build-libphonenumber'...
[11:55:58] 'build-libphonenumber' errored after 4.78 ms
[11:55:58] Error: spawn ./build/apache-ant-1.10.5/bin/ant ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
[11:55:58] 'build' errored after 19 s
[11:55:58] 'default' errored after 20 s
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

chrisf@_______ /cygdrive/c/dev/awesome-phonenumber (master)
$ ll build/apache-ant-1.10.5/bin/ant*
-rwxr-xr-x+ 1 chrisf None 11557 Jul 10  2018 build/apache-ant-1.10.5/bin/ant
-rw-r--r--+ 1 chrisf None  7470 Jul 10  2018 build/apache-ant-1.10.5/bin/ant.bat
-rw-r--r--+ 1 chrisf None  2855 Jul 10  2018 build/apache-ant-1.10.5/bin/ant.cmd
-rw-r--r--+ 1 chrisf None  3409 Jul 10  2018 build/apache-ant-1.10.5/bin/antenv.cmd
-rwxr-xr-x+ 1 chrisf None   861 Jul 10  2018 build/apache-ant-1.10.5/bin/antRun
-rw-r--r--+ 1 chrisf None  1532 Jul 10  2018 build/apache-ant-1.10.5/bin/antRun.bat
-rwxr-xr-x+ 1 chrisf None  2117 Jul 10  2018 build/apache-ant-1.10.5/bin/antRun.pl
```

**Comment by grantila** [comment]
Yeah the symbol needs to be *exported*. I haven't compiled on Windows, I guess you need Java in order to run `ant`..

**Comment by chris-findlay** [comment]
Ah, thanx heaps - missed that completely.
Re java for ant - that makes sense I guess.
